# This is a simple ansible playbook to deploy upgrades to sourcefire.
#    Make sure you select the correct upgrade to deploy!

---
- hosts: all # Need to limit to actual groups, will do this after testing.
  become: true
