# This is a simple ansible playbook to deploy upgrades to sourcefire.
#    Make sure you select the correct upgrade to deploy!

---
- hosts: all # Need to limit to actual groups, will do this after testing.
  tasks:
  - name: Copy Upgrade to Remote system
    become: true
    copy:
      src: "{{ update_path }}"
      dest: "/var/sf/updates/"
  - name: Install Update
    become: true
    shell: "bash /usr/local/sf/bin/install_update.pl /var/sf/updates/{{ upgrade_path }}"
