# This is an ansible playbook to restrict the use of SSH passwords and allow users to sudo without a password for use with ansible scripts.
---
- hosts: all
  remote_user: admin
  tasks:
  - name: Deny Empty Passwords
    become: true
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PermitEmptyPasswords '
      line: 'PermitEmptyPasswords no'
  - name: Deny Password Based Login
    become: true
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PasswordAuthentication '
      line: 'PasswordAuthentication no'
  - name: Disable PAM authentication for SSH
    become: true
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^UsePAM '
      line: 'UsePAM no'
