# This is an ansible playbook to restrict the use of SSH passwords and allow users to sudo without a password for use with ansible scripts.
---
- hosts: all
  remote_user: "{{ user }}"
  tasks:
  - name: Deny Empty Passwords
    become: true
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PermitEmptyPasswords '
      line: 'PermitEmptyPasswords no'
  - name: Deny Password Based Login
    become: true
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^PasswordAuthentication '
      line: 'PasswordAuthentication no'
  - name: Disable PAM authentication for SSH
    become: true
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regexp: '^UsePAM '
      line: 'UsePAM no'
  - name: Allow user 'admin' to sudo without password
    become: true
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^admin ALL='
      line: 'admin ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  # This really should be a handler.
  - name: Restart SSH Daemon
    become: true
    shell: /etc/rc.d/init.d/sshd restart
