# Simple playbook to reboot hosts
---
- hosts: all
  - name: Rebooting Systems
    shell: reboot
    async: 0
    poll: 0
  - name: Waiting for Server
    local_action: wait_for host={{ ansible_ssh_host }} state=started
