# A simple Ansible Playbook to remove the manager from the sensor
#   configuration in the event of an emergency, such as having to
#   rebuild the manager, or if you need to remove the manager without
#   reseting the config on sensor. If you remove the sensor from the 
#   manager UI or 'remove_peer.pl' (same thing), it will revert to 
#   clish as the default shell.
---
- hosts: FirePower_Sensors
  remote_user: "{{ user }}"
  tasks:
  # Remove Manager on Sensor
  - name: Removing Manager on Sensor
    become: true
    shell: "/usr/local/sf/bin/sfcli.pl not managed"

  # Remove Sensor on Manager
  - name: Removing Sensor on Manager
    become: true
    shell: "/usr/local/sf/bin/remove_peer.pl {{ inventory_hostname }}"
    delegate_to: "{{ manager_ip }}"
