---
- hosts: all
  remote_user: admin
  tasks:
  - name: Remove Previous Splunk Install
    become: true
    shell: rm -rf /opt/splunkforwarder/
  - name: Deploy Splunk
    become: true
    copy:
      src: "{{ splunkforwarder_path }}"
      dest: "~/SplunkUF.tgz"
  - name: Extract SplunkUF
    become: true
    shell: tar -xzf "/root/SplunkUF.tgz" -C "/opt"
  - name: Configure SplunkUF to log /var/log
    become: true
    shell: /opt/splunkforwarder/bin/splunk --accept-license add monitor "/var/log"
  - name: Configure SplunkUF to log to a splunk server
    become: true
    shell: /opt/splunkforwarder/bin/splunk add forward-server {{ splunk_server_address }}:{{ splunk_server_port }}
  - name: Configure SplunkUF to log /var/log
    become: true
    shell: /opt/splunkforwarder/bin/splunk --accept-license start
  - name: Leverage Cron to start SplunkUF on boot
    become: true
    lineinfile:
      path: /etc/crontab
      state: present
      regexp: '^@reboot    root /opt/splunkforwarder/bin/splunk start'
      line: '@reboot    root /opt/splunkforwarder/bin/splunk start'
  - name: Remove Compressed File
    become: true
    shell: rm -f "~/SplunkUF.tgz"
