# This is a down and dirty ansible playbook to get the job done. This could potentially
#    be very dangerous to run if you aern't sure what you're doing. As always, test!
#
# As well, this 'should' work on any unix system that can execute the binaries. However, 
#   there is a reason this isn't common place. Namely stability and upgradability, but this
#   script should allow for the latter and the former is really all about the host. I have 
#   expierenced a good ammount of success with this and would like to test it farther for
#   appliance type systems.

---
- hosts: all
  remote_user: "{{ user }}"
  tasks:
  - name: Stop SplunkUF if Running and Force Remove Previous Install
    become: true
    shell: if [ -f "/opt/splunkforwarder/bin/splunk" ]; then /opt/splunkforwarder/bin/splunk stop; rm -rf /opt/splunkforwarder; fi
  - name: Ensure /opt exists
    become: true
    file:
      path: /opt
      state: directory
      owner: root
      group: root
      mode: 0755
  - name: Deploy Splunk
    become: true
    copy:
      src: "{{ splunkforwarder_path }}"
      dest: "~/SplunkUF.tgz"
  - name: Extract SplunkUF
    become: true
    shell: tar -xzf "/root/SplunkUF.tgz" -C "/opt"
  - name: Configure SplunkUF to log /var/log
    become: true
    shell: /opt/splunkforwarder/bin/splunk --accept-license add monitor "/var/log"
  - name: Configure SplunkUF to log to a splunk server
    become: true
    shell: /opt/splunkforwarder/bin/splunk add forward-server {{ splunk_server_address }}:{{ splunk_server_port }}
  - name: Start SplunkUF
    become: true
    shell: /opt/splunkforwarder/bin/splunk --accept-license start
  # SourceFire uses a weird init.d structure. Chances are I can just create a sim link to rc.d but this is the quick work around for now.
  - name: Leverage Cron to start SplunkUF on boot
    become: true
    lineinfile:
      path: /etc/crontab
      state: present
      regexp: '^@reboot    root /opt/splunkforwarder/bin/splunk start'
      line: '@reboot    root /opt/splunkforwarder/bin/splunk start'
  - name: Remove Compressed File
    become: true
    shell: rm -f "~/SplunkUF.tgz"
