---
- hosts: all
  remote_user: admin
  vars:
    splunkforwarder_path: ~/splunkforwarder.tgz
  tasks
  - name: Deploy SplunkUF
    become: true
    template:
      src: {{ splunkforwarder_path }}
      dest: ~/SplunkUF.tgz
  - name: Extract SplunkUF
    become: true
      shell: tar xvzf SplunkUF.tgz -C /opt
  - name: Configure SplunkUF to log /var/log
      become: true
      shell: /opt/SplunkUF/bin/splunk add monitor /var/log
  - name: Configure SplunkUF to log to a splunk server
    become: true
      shell: /opt/SplunkUF/bin/splunk add {{ splunk_server_address }}:{{ splunk_server_port }}
  - name: Leverage Cron to start SplunkUF on boot
    become: true
    lineinfile:
      path: /etc/crontab
      state: present
      regexp: '^@reboot    root /opt/splunkforwarder/bin/splunk start'
      line: '@reboot    root /opt/splunkforwarder/bin/splunk start'
