---
- hosts: all
  remote_user: admin
  vars:
    splunkforwarder_path: ~/splunkforwarder.tgz
  tasks
  - name: Deploy SplunkUF
    become: true
    template:
      src: {{ splunkforwarder_path }}
      dest: ~/SplunkUF.tgz
